Barb/urls.py
from django.contrib import admin
from django.urls import path, include
from Controle_Financeiro import views

urlpatterns = [
    path('', include('Controle_Financeiro.urls')),  
]

Controle_Financeiro/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('transacoes', views.transacoes, name="transacoes"),
    path('transacao_add', views.transacao_add, name='transacao_add'),
    path('transacao_edit/<int:transacao_id>/', views.transacao_edit, name='transacao_edit'),
    path('transacao_delete/<int:transacao_id>', views.transacao_delete, name='transacao_delete'),
]

Controle_Financeiro/models.py
from django.db import models
import datetime


# Create your models here.
class Transacao(models.Model):
    descricao= models.CharField(max_length=200)
    valor = models.FloatField(default=0.00)
    data = models.CharField(max_length=12)


    def __str__(self):
        return f"{self.descricao} - {self.valor} - {self.data}"

Controle_Financeiro/forms.py
from .models import Transacao
from django import forms
from logging import PlaceHolder

class TransacaoForm(forms.ModelForm):
    class Meta:
        model = Transacao
        fields = ('descricao', 'valor', 'data')

Controle_Financeiro/views.py
from django.shortcuts import render, redirect
from  .models import Transacao
from .forms import TransacaoForm

# Create your views here.
def home(request):
    transacoes = Transacao.objects.all()
    context ={
        'transacoes': transacoes
   }
    return render(request, 'controle/home.html', context)

def transacoes(request):
   transacoes = Transacao.objects.all()
   context ={
        'transacoes': transacoes
   }
   return render(request, 'controle/transacoes.html', context)

def transacao_add(request):
    form = TransacaoForm(request.POST or None)
    print(form)
    if request.POST:
        if form.is_valid():
            form.save()
            return redirect('home')     

    return render(request, 'controle/transacao_add.html', {'form': form })

def transacao_edit(request, transacao_id):
    transacao = Transacao.objects.get(id=transacao_id)  
    print (transacao) 
    form = TransacaoForm(request.POST or None, instance=transacao)
    if request.POST:
            if form.is_valid():
                form.save()
                return redirect('home')
        
    context ={
        'transacao':transacao,
        'form':form
    }    
    return render(request, 'controle/transacao_edit.html',context)

def transacao_delete(request, transacao_id):
    transacao = Transacao.objects.get(id= transacao_id)
    transacao.delete() 
    return redirect('home')

Controle_Financeiro/templates/controle/home.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'favicon/favicon.ico'%}" type="image/x-icon">
    <title>Controle Financeiro Barbearia</title>
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="{% static 'js/scripts.js' %}" defer></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link
    href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,400;0,700;1,100;1,400;1,700&display=swap"
    rel="stylesheet">
    <!-- META NAME & DESCRIPTION -->
    <meta name="author" content="Hideraldo Rodrigues">
    <meta name="description" content="Seu app de controle de finanças.">
</head>
<body>
    <header>
        <img src="{% static 'img/eder.jpg' %}" alt="Logo Barb">
        <h1>CONTROLE FINANCEIRO " EDER BARBERSHOP "</h1>
    </header>

    <main class="container">
        <section id="balance">
            <h2 class="sr-only">Balanço</h2>
            <div class="card">
                <h3>
                    <span>
                        Entradas
                    </span>
                    <img src="{% static 'img/income.svg'%}" alt="Imagem de entradas">
                </h3>    
                <p id="incomeDisplay">R$ 0,00</p>
            </div>
            <div class="card">
                <h3>
                    <span>
                        Saídas
                    </span>
                    <img src="{% static 'img/expense.svg'%}" alt="Imagem de saídas">
                </h3>
                <p id="expenseDisplay">R$ 0,00</p>
            </div>
            <div class="card total">
                <h3>
                    <span>
                        Total
                    </span>
                    <img src="{% static 'img/total.svg'%}" alt="Imagem de total">
                </h3>
                <p id="totalDisplay">R$ 0,00</p>
            </div>
        </section>
        <a href="#" id="abrirModal" class="button new">+ Nova transação</a>

        <!-- Modal -->
     <div id="modal" class="modal" style="display:none;">
        <div class="modal-content">
            <span class="close" id="fecharModal">&times;</span>
            <h2>Nova Transação</h2>
            <form action="{% url 'transacao_add' %}" method="post"> 
                {% csrf_token %}
                <div class="input-group">
                    <label class="sr-only" for="id_descricao">Descrição</label>
                    <input type="text" id="id_descricao" name="descricao" placeholder="Descrição" required>
                </div>
                <div class="input-group">
                    <label class="sr-only" for="id_valor">Valor</label>
                    <input type="number" step="0.01" id="id_valor" name="valor" placeholder="0,00" required>
                    <small>Use o sinal " - " (negativo) para despesas e " , " (vírgula) para casas decimais</small>
                </div>
                <div class="input-group">
                    <label class="text" for="id_data"></label>
                    <input type="date" id="id_data" name="data" required>
                </div>
                <div id="att" class="attention sr-only">
                    <small>Por favor, preencha todos os campos!</small>
                </div>
                <div class="input-group actions">
                    <a onclick="document.getElementById('modal').style.display='none'" href="#" class="button cancel">Cancelar</a>
                    <button type="submit">Salvar</button>
                </div>
            </form>
        </div>
    </div>
    <!-- Modal de edição -->
<div id="modalEdit" class="modal" style="display:none;">
    <div class="modal-content">
        <span class="close" id="fecharModalEdit">&times;</span>
        <h2>Editar Transação</h2>
        <form id="editForm" action="{% url 'transacao_edit' 0 %}" method="post">
            {% csrf_token %}
            <div class="input-group">
                <label class="sr-only" for="editDescricao">Descrição</label>
                <input type="text" id="editDescricao" name="descricao" placeholder="Descrição" required>
            </div>
            <div class="input-group">
                <label class="sr-only" for="editValor">Valor</label>
                <input type="number" step="0.01" id="editValor" name="valor" placeholder="0,00" required>
            </div>
            <div class="input-group">
                <label class="sr-only" for="editData">Data</label>
                <input type="date" id="editData" name="data" required>
            </div>
            <div class="input-group actions">
                <a onclick="document.getElementById('modalEdit').style.display='none'" href="#" class="button cancel">Cancelar</a>
                <button type="submit">Salvar</button>
            </div>
        </form>
    </div>
</div>

        <section id="transaction">
            <h2 class="sr-only">Transações</h2>
            <div class="table-container">
                <table id="data-table">
                    <thead>
                        <tr>
                            <th>Descrição</th>
                            <th>Valor</th>
                            <th>Data</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for transacao in transacoes %}
                        <tr>
                            <td>{{transacao.descricao}}</td>
                            <td>{{transacao.valor}}</td>
                            <td>{{transacao.data}}</td>
                            <td>
                                <a href="#" class="btn abrirModalEdit" data-id="{{ transacao.id }}" 
                                data-descricao="{{ transacao.descricao }}" data-valor="{{ transacao.valor }}" data-data="{{ transacao.data }}">EDITAR</a>
                                <img src="{% static 'img/edit.svg' %}" alt="Editar">
                                <a href="{% url 'transacao_delete' transacao.id %}"class="btn">EXCLUIR</a>
                                <img src="{% static 'img/trash.svg' %}" alt="Excluir" class="action-icon">
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </section>

    </main>
    <footer>
        <p>&copy; <span id="anoAtual"></span> Eder BarberShop. Todos os direitos reservados.</p>
    </footer>
    
   
</body>
</html>

Controle_Financeiro/templates/controle/transacao_add.html
            <h2>Nova Transação</h2>
            <form action="{% url 'transacao_add' %}" method="post"> {% csrf_token %}

                <div class="input-group">
                    <label class="sr-only" for="id_descricao">
                        Descrição
                    </label>
                    <input type="text" id="id_descricao" name="descricao" placeholder="Descrição" required>
                </div>
                <div class="input-group">
                    <label class="sr-only" for="id_valor">Valor</label>
                    <input type="number" step="0.01" id="id_valor" name="valor" placeholder="0,00" required>
                    <small>Use o sinal " - " (negativo) para despesas e " , " (vírgula) para casas
                        decimais</small>
                </div>
                <div class="input-group">
                    <label class="text" for="id_data"></label>
                    <input type="date" id="id_data" name="data" required>
                </div>
                <div id="att" class="attention sr-only">
                    <small>Por favor, preencha todos os campos!</small>
                </div>
                <div class="input-group actions">
                    <a onclick="Modal.close()" href="#" class="button cancel">Cancelar</a>
                    <button type="submit">Salvar</button>
                </div>
            </form>

Controle_Financeiro/templates/controle/transacao_edit.html
<div class="card"></div>
    <div class="card-body">
        <h1>EDITAR TRANSAÇÔES</h1>
        <hr>
        <form action="{% url 'transacao_edit' transacao.id %}" method="post">
            {% csrf_token %}
            <div class="input-group">
                <label class="sr-only" for="descricao">
                    Descrição
                </label>
                <input type="text" id="descricao" name="descricao" placeholder="Descrição">
            </div>
            <div class="input-group">
                <label class="sr-only" for="valor">Valor</label>
                <input type="number" step="0.01" id="valor" name="valor" placeholder="0,00">
                <small>Use o sinal " - " (negativo) para despesas e " , " (vírgula) para casas
                    decimais</small>
            </div>
            <div class="input-group">
                <label class="sr-only" for="data">Data</label>
                <input type="date" id="data" name="data">
            </div>
            <div id="att" class="attention sr-only">
                <small>Por favor, preencha todos os campos!</small>
            </div>
            <div class="input-group actions">
            </div>
            <button class="btn btn-success" type="submit">SALVAR</button>


        </form>    
    </div>
</div>

Controle_Financeiro/templates/controle/transacoes.html
<section id="transaction">
    <h2 class="sr-only">Transações</h2>
    <a href="#" onclick="Modal.open()" class="button new">+ Nova transação</a>
    <div class="table-container">
        <table id="data-table">
            <thead>
                <tr>
                    <th>Descrição</th>
                    <th>Valor</th>
                    <th>Data</th>
                    <th></th> <!-- Celula vazia para os botões de ação -->
                </tr>
            </thead> 
            <tbody>
                {% for transacao in transacoes %}
                <tr>
                    <td>{{transacao.descricao}}</td>
                    <td>{{transacao.valor}}</td>
                    <td>{{transacao.data}}</td>
                    <td>
                       <a class="btn btn-warning" href="{% url 'transacao_edit' transacao.id %}">EDITAR</a>
                       <a class="btn btn-danger" href="{% url 'transacao_delete' transacao.id %}">EXCLUIR</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</section>